services:
    DieSchittigs\ContaoContentApiBundle\Controller\ContentApiController:
        autowire: true
        autoconfigure: true
        arguments:
            - '@contao.framework'
        tags:
            - controller.service_arguments
